import { LookerEmbedUser } from './types'

export const user: LookerEmbedUser = {
  external_user_id: 'embed-user-1',
  first_name: 'Johnny',
  last_name: 'Embed',
  session_length: 3600,
  force_logout_login: true,
  external_group_id: 'embed-group-1',
  group_ids: [],
  permissions: [
    'access_data',
    'see_user_dashboards',
    'explore',
    // 'download_without_limit',
    // 'see_lookml_dashboards',
    'see_looks',
    // 'create_table_calculations',
    'save_content',
    // 'create_public_looks',
    // 'download_with_limit',
    // 'schedule_look_emails',
    // 'schedule_external_look_emails',
    // 'create_alerts',
    // 'follow_alerts',
    // 'send_to_s3',
    // 'send_to_sftp',
    // 'send_outgoing_webhook',
    // 'send_to_integration',
    // 'see_sql',
    // 'see_lookml',
    // 'develop',
    // 'deploy',
    // 'support_access_toggle',
    // 'clear_cache_refresh',
    // 'see_drill_overlay',
    // 'manage_spaces',
    // 'manage_homepage',
    // 'manage_models',
    // 'create_prefetches',
    // 'login_special_email',
    // 'embed_browse_spaces',
    // 'embed_save_shared_space',
    // 'see_alerts',
    // 'see_queries',
    // 'see_logs',
    // 'see_users',
    // 'sudo',
    // 'see_schedules',
    // 'see_pdts',
    // 'see_datagroups',
    // 'update_datagroups',
    // 'see_system_activity',
    // 'mobile_app_access',
  ],
  models: ['Runner', 'thelook', 'geo-test'],
  user_attributes: { locale: 'en_US' },
}
